tpd: 
  appconfig: 
    spanish-alias: tpd-es
    english-alias: tpd-en
    spanish-port: 8081
    english-port: 8082
    peer1-address: peer1:8761
    peer2-address: peer2:8762
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true

---
spring:
  profiles: english
  application:
    name: ${tpd.appconfig.english-alias}
  sleuth:
    sampler:
      rate: 100

    
server:
  port: ${tpd.appconfig.english-port}
  
eureka:
  client:
    service-url:
      defaultZone: http://${tpd.appconfig.peer1-address}/eureka/,http://${tpd.appconfig.peer2-address}/eureka/

demo-tpd-es: 
  ribbon: 
    DeploymentContextBasedVipAddresses: ${tpd.appconfig.spanish-alias}
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
    
---
spring:
  profiles: spanish
  application:
    name: ${tpd.appconfig.spanish-alias}
  sleuth:
    sampler:
      rate: 100
server:
  port: ${tpd.appconfig.spanish-port}
eureka:
  client:
    service-url:
      defaultZone: http://${tpd.appconfig.peer2-address}/eureka/,http://${tpd.appconfig.peer1-address}/eureka/
  
demo-tpd-en: 
  ribbon: 
    DeploymentContextBasedVipAddresses: ${tpd.appconfig.english-alias}
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
  
      
